baseURL: "https://kasreti.github.io"
title: "kasreti's crib"
footnoteReturnLinkContents: "↩"
permalinks:
  post: /:year/:month/:title/
params:
  Subtitle: "test."
  AuthorName: "Kasreti"
  GitHubUser: "Kasreti"
  ListOfFoo:
    - "foo1"
    - "foo2"
  SidebarRecentLimit: 5
theme: hugo-blog-awesome-1.15.0
