title = "kasreti's crib"
description = "welcome to the crib"
baseURL = "https://kasreti.github.io"

languageCode = 'en-ca'
defaultContentLanguage = "en-ca"

theme = "blog"
defaultColor = "light" 
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]
mainSections = ['posts']

[params]
	favicon = true
	toc = true
	tocOpen = true
	goToTop = true
	
[[params.socialIcons]]
	name = "github"
	url = "https://github.com/kasreti"

[[params.socialIcons]]
	name = "twitter"
	url = "https://twitter.com/kasreti"

[params.author]
		avatar = "author/pfp.png"
		intro = "kasreti's crib"
		name = "Kasreti"
		description = "the unhinged ramblings of the most successful social media influencer of the decade"

[services]
	[services.disqus]
		shortname = 'dacomments'

contentDir = "content"
weight = 1
[menu]
	[[menu.main]]
		# The page reference (pageRef) is useful for menu highlighting
		# When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
		pageRef="/"
		name = 'home'
		url = '/'
		weight = 10
	[[menu.main]]
		pageRef="about"
		name = 'about'
		url = '/about/'
		weight = 20
	[[menu.main]]
		pageRef="posts"
		name = 'all posts'
		url = '/posts/'
		weight = 30
	


